### ISSUE TITLE
swarmcallback

### ISSUE THREAD

**Issue by imliinyi** [HAIRLAB/DeceFL#1]
when i run your code, its show me 'no model named swarm'. what should i do? 

>

**Comment by JinDou1210** [comment]
> when i run your code, its show me 'no model named swarm'. what should i do?
> 
> >

Experiments of swarm-learning must be deployed in accordance with the steps given by [https://github.com/HewlettPackard/swarm-learning](url) . Dependent libraries such as swarm are all in their docker containers. Hope it helps you.
