### ISSUE TITLE
It doesn't run

### ISSUE THREAD

**Issue by chenyikuan1230** [HAIRLAB/DeceFL#2]
How to solve this problem？Do you want to download the dataset and save it in the corresponding directory？thank you！！！

Traceback (most recent call last):
  File "C:/Users/86188/Desktop/DeceFL-main/ConsensusExample/defed.py", line 79, in <module>
    with open(f'../save/node{args.num_users}/objects/defed_ini_state_p{args.p}.pkl', 'wb') as f:
FileNotFoundError: [Errno 2] No such file or directory: '../save/node8/objects/defed_ini_state_p0.3.pkl'

**Comment by JinDou1210** [comment]
You need to create the directory '../save/node8/objects' to save the experiment results.  And we'll upload the dataset later. Thank you for your comments!

**Comment by chenyikuan1230** [comment]
C:\Users\86188\Desktop\DeceFL-main\CWRU>CUDA_VISIBLE_DEVICES=0 nohup python defed.py --dataset cwru --gpu 1 --iid 1 --unequal 0 --num_channels 1 --model dnn --epochs 300 --local_ep 30 --l
r 0.1 --step_size 20 --local_bs 64 --num_users 4 --p 0.9 --num_classes 4 --seed 1 > ../result/node4/defed_cwru_dnn_iid_r300_p0.9_seed1.txt 2>&1 &
系统找不到指定的路径。
Where is this file？Do you have to run this on Linux or windows

**Comment by JinDou1210** [comment]
Just create the directory '../result/node4'. And you'd better run this on Linux. Thank you for your comments!
